// <auto-generated />
using System;
using Lcw_Project.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lcw_Project.Migrations
{
    [DbContext(typeof(LcWaikikiProjectContext))]
    [Migration("20211008232447_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Turkish_CS_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lcw_Project.Entities.LcwCustomer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerSurname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Lcw_Customer");
                });

            modelBuilder.Entity("Lcw_Project.Entities.LcwCustomerOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Lcw_CustomerOrder");
                });

            modelBuilder.Entity("Lcw_Project.Entities.LcwCustomerOrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CustomerOrderId")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Lcw_CustomerOrderItem");
                });

            modelBuilder.Entity("Lcw_Project.Entities.LcwProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Lcw_Product");
                });

            modelBuilder.Entity("Lcw_Project.Entities.LcwCustomerOrder", b =>
                {
                    b.HasOne("Lcw_Project.Entities.LcwCustomer", "Customer")
                        .WithMany("LcwCustomerOrders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Lcw_CustomerOrder_Lcw_Customer")
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Lcw_Project.Entities.LcwCustomerOrderItem", b =>
                {
                    b.HasOne("Lcw_Project.Entities.LcwCustomerOrder", "CustomerOrder")
                        .WithMany("LcwCustomerOrderItems")
                        .HasForeignKey("CustomerOrderId")
                        .HasConstraintName("FK_Lcw_CustomerOrderItem_Lcw_CustomerOrder")
                        .IsRequired();

                    b.HasOne("Lcw_Project.Entities.LcwProduct", "Product")
                        .WithMany("LcwCustomerOrderItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_Lcw_CustomerOrderItem_Lcw_Product")
                        .IsRequired();

                    b.Navigation("CustomerOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lcw_Project.Entities.LcwCustomer", b =>
                {
                    b.Navigation("LcwCustomerOrders");
                });

            modelBuilder.Entity("Lcw_Project.Entities.LcwCustomerOrder", b =>
                {
                    b.Navigation("LcwCustomerOrderItems");
                });

            modelBuilder.Entity("Lcw_Project.Entities.LcwProduct", b =>
                {
                    b.Navigation("LcwCustomerOrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
